const icon_map = new Map([
    ["partly-cloudy-night", "cloudy"],
    ["snow", "snow"],
    ["cloudy", "cloudy"],
    ["rain", "rain"],
    ["clear-night", "clear"],
    ["Partly cloudy", "cloudy"],
    ["Cloudy", "cloudy"],
    ["Sunny", "clear"],
    ["Clear","clear"],
    ["Overcast", "cloudy"],
    ["Patchy rain possible", "rain"],
    ["Patchy snow possible", "snow"],
    ["Patchy sleet possible", "snow"],
    ["Patchy freezing drizzle possible", "rain"],
    ["Thundery outbreaks possible", "storm"],
    ["Blowing snow", "snow"],
    ["Blizzard", "snow"],
    ["Fog", "cloudy"],
    ["Freezing fog", "cloudy"],
    ["Patchy light drizzle", "rain"],
    ["Light drizzle", "rain"],
    ["Freezing drizzle", "rain"],
    ["Heavy freezing drizzle", "rain"],
    ["Patchy light rain", "rain"],
    ["Light rain", "rain"],
    ["Moderate rain at times", "rain"],
    ["Moderate rain",  "rain"],
    ["Heavy rain at times", "rain"],
    ["Heavy rain", "rain"],
    ["Light freezing rain", "rain"],
    ["Moderate or heavy freezing rain", "rain"],
    ["Light sleet", "rain"],
    ["Light sleet", "rain"],
    ["Moderate or heavy sleet", "rain"],
    ["Patchy light snow", "snow"],
    ["Light snow", "snow"],
    ["Patchy moderate snow", "snow"],
    ["Moderate snow", "snow"],
    ["Patchy heavy snow", "snow"],
    ["Heavy snow", "snow"],
    ["Ice pellets", "rain"],
    ["Light rain shower", "rain"],
    ["Moderate or heavy rain shower", "rain"],
    ["Torrential rain shower", "rain"],
    ["Light sleet showers", "rain"],
    ["Moderate or heavy sleet showers", "rain"],
    ["Light snow showers", "snow"],
    ["Moderate or heavy snow showers", "snow"],
    ["Moderate or heavy showers of ice pellets", "snow"],
    ["Patchy light rain with thunder", "rain"],
    ["Moderate or heavy rain with thunder", "rain"],
    ["Patchy light snow with thunder", "snow"],
    ["Moderate or heavy snow with thunder", "snow"],
    ["r", "rain"],
    ["t", "storm"],
    ["s", "snow"],
    ["a", "cloudy"],
    ["c", "cloudy"]


])

export default icon_map;