let common_object = {
    "city":"",
    "weather_today":{
        "03:00:00":{
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "06:00:00":{
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "09:00:00":{
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "12:00:00":{
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "15:00:00":{
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "18:00:00":{
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "21:00:00":{
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "00:00:00":{
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "today_advice":""
    },
    "weather_week":{
        "first_day":{
            "data":"",
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "second_day":{
            "data":"",
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "three_day":{
            "data":"",
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "four_day":{
            "data":"",
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "five_day":{
            "data":"",
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "six_day":{
            "data":"",
            "img":"",
            "air_temp":"",
            "speed_wind":""
        },
        "seven_day":{
            "data":"",
            "img":"",
            "air_temp":"",
            "speed_wind":""
        }
    }
}

export default common_object;